

###
POST http://localhost:3000/run-job
Content-Type: application/json

{
  "scriptPath": "C:/Users/dinhtiendat190196/Desktop/Recording 7_15_2024 at 7_31_07 AM.js",
  "listProfilePaths": [
    "C:/Users/dinhtiendat190196/Desktop/profile-data/72656530-4025-11ef-a94f-eb4a4d0c3af4",
    "C:/Users/dinhtiendat190196/Desktop/profile-data/770ca620-4025-11ef-a94f-eb4a4d0c3af4",
    "C:/Users/dinhtiendat190196/Desktop/profile-data/799ee9c0-4025-11ef-a94f-eb4a4d0c3af4"
  ]
}
