

###
POST http://localhost:3000/run-job
Content-Type: application/json

{
  "scriptPath": "C:/Users/dinhtiendat190196/Desktop/Recording 7_22_2024 at 10_09_42 AM.js",
  "listProfilePaths": [
    "C:/Users/dinhtiendat190196/Desktop/profile-data/5c0cfaf0-47d7-11ef-a0ea-0db742554e1b"
  ]
}
